name: ✨ Feature Request
description: Suggest a new feature or improvement for Shoy
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe
      placeholder: |
        Example: I'm always frustrated when...
        
        Currently, Shoy doesn't support X, which makes it difficult to Y.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What do you want to happen?
      placeholder: Describe how you envision this feature working...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternative solutions or features you've considered
      placeholder: |
        - Alternative 1
        - Alternative 2
        - etc.

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature benefit you or other users?
      placeholder: Explain your use case in detail...
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: If applicable, provide a code example of how you'd use this feature
      placeholder: |
        ```typescript
        const store = new Shoy(initialState);
        // How you'd use the new feature
        ```
      render: typescript

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of Shoy would this feature impact?
      options:
        - Core Store (Shoy class)
        - React Hooks (useGet, useApply)
        - Time-travel / History
        - Type Definitions
        - Performance
        - Developer Experience
        - Documentation
        - Build / Tooling
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checked
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have considered the impact on backward compatibility
          required: false

